### PR TITLE
fix: limit `wrap_sys_device` to UNIX targets

### PR DESCRIPTION
**Pull request by xJonathanLEI**
This PR fixes a compilation error on Windows introduced by #2.

### CODE REVIEW

**Comment by xJonathanLEI** [comment]
@joshieDo Sorry I didn't try compiling on Windows for the last PR. Turns out it no longer works after the changes.

So I just checked `rusb` and they actually also limit a wrapper around this same method to UNIX only:

https://github.com/a1ien/rusb/blob/eb88e29df945a1acfa03cc30220c9a9542234c4b/src/context.rs#L84-L86
